# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iSL-KD2RmGbI-9Fy9CcXr-fTzIlSKHrd
"""

Cv1 = {"Ad": "Furkan", "Soyad": "Akkulak", "E-mail": "akkulak.furkan26@gmail.com", "Cinsiyet": "Erkek", "Adres": "Eskişehir"}
Cv2 = {"Ad": "Onur", "Soyad": "Sever", "E-mail": "redkulus26@hotmail.com", "Cinsiyet": "Erkek", "Adres": "Eskişehir" }
Cv3 = {"Ad": "Murat", "Soyad": "Türker", "E-mail": "asdasd", "Cinsiyet": "Erkek", "Adres": "Eskişehir"}
Cv4 = {"Ad": "Simay", "Soyad": "Olgaç", "E-mail": "asdasd", "Cinsiyet": "Kadın", "Adres": "İzmir"}
Cv5 = {"Ad": "Furkan Ahmet", "Soyad": "Orhan", "E-mail": " ", "Cinsiyet": "Erkek", "Adres": "Eskişehir"}
for t in range (6):
  print("-"*20)
  if t == 0:
    print("İsim:", Cv1["Ad"])
    print("Soyisim:", Cv1["Soyad"])
    print("E-posta:", Cv1["E-mail"])
    print("Telefon:", Cv1["Cinsiyet"])
    print("Adres:", Cv1["Adres"])
  elif t == 1:
    print("İsim:", Cv2["Ad"])
    print("Soyisim:", Cv2["Soyad"])
    print("E-posta:", Cv2["E-mail"])
    print("Telefon:", Cv2["Cinsiyet"])
    print("Adres:", Cv2["Adres"])
  elif t == 2:
    print("İsim:", Cv3["Ad"])
    print("Soyisim:", Cv3["Soyad"])
    print("E-posta:", Cv3["E-mail"])
    print("Telefon:", Cv3["Cinsiyet"])
    print("Adres:", Cv3["Adres"])
  elif t == 3:
    print("İsim:", Cv4["Ad"])
    print("Soyisim:", Cv4["Soyad"])
    print("E-posta:", Cv4["E-mail"])
    print("Telefon:", Cv4["Cinsiyet"])
    print("Adres:", Cv4["Adres"])
  elif t == 4:
    print("İsim:", Cv5["Ad"])
    print("Soyisim:", Cv5["Soyad"])
    print("E-posta:", Cv5["E-mail"])
    print("Telefon:", Cv5["Cinsiyet"])
    print("Adres:", Cv5["Adres"])
  else:
    print("Başvuran Sayısı: 5")